# RETS Resource config entity.
drealty.drealty_resource.*:
  type: mapping
  label: 'RETS Resource'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'System Name'
    connection:
      type: drealty_connection
      label: 'Connection'

# Connection config entity.
drealty.drealty_connection.*:
  type: mapping
  label: 'DRealty Connection'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
      translatable: true
    status:
      type: boolean
      label: 'Active'
    rets:
      type: float
      label: 'RETS'
    url:
      type: string
      label: 'URL'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    ua_string:
      type: string
      label: 'User-Agent string'
    ua_password:
      type: string
      label: 'User-Agent password'
    use_interealty_auth:
      type: boolean
      label: 'Use interealty authentication'
    force_basic_auth:
      type: boolean
      label: 'Force basic authentication'
    use_compression:
      type: boolean
      label: 'Use compression'
    disable_encoding_fix:
      type: boolean
      label: 'Disble encoding fix'
    debug_mode:
      type: boolean
      label: 'Debug mode'
    nomap_mode:
      type: boolean
      label: 'No map mode'

# Listing type config entity.
drealty.type.*:
  type: config_entity
  label: 'Listing type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: drealty_listing_type.third_party.[%key]

condition.plugin.drealty_listing_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        - type: string
