# Connection config entity.
drealty.drealty_connection.*:
  type: mapping
  label: 'DRealty Connection'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Name'
      translatable: true
    status:
      type: boolean
      label: 'Active'
    rets:
      type: float
      label: 'RETS'
    url:
      type: string
      label: 'URL'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    ua_string:
      type: string
      label: 'User-Agent string'
    ua_password:
      type: string
      label: 'User-Agent password'
    use_interealty_auth:
      type: boolean
      label: 'Use interealty authentication'
    force_basic_auth:
      type: boolean
      label: 'Force basic authentication'
    use_compression:
      type: boolean
      label: 'Use compression'
    disable_encoding_fix:
      type: boolean
      label: 'Disble encoding fix'
    debug_mode:
      type: boolean
      label: 'Debug mode'
    nomap_mode:
      type: boolean
      label: 'No map mode'

# Listing type config entity.
drealty.type.*:
  type: config_entity
  label: 'Listing type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        drealty:
          type: drealty.settings.drealty

# Listing type module settings.
drealty.settings.drealty:
  type: mapping
  label: 'Listing type settings'
  mapping:
    options:
      type: mapping
      label: 'Publishing options'
      mapping:
        status:
          type: boolean
          label: 'Published'
        featured:
          type: boolean
          label: 'Featured'
        revision:
          type: boolean
          label: 'Create new revision'
