# Connection config entity.
drealty.drealty_connection.*:
  type: mapping
  label: 'DRealty Connection'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Name'
      translatable: true
    url:
      type: string
      label: 'URL'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    agent_string:
      type: string
      label: 'User Agent String'
    agent_password:
      type: string
      label: 'User Agent Password'

# Listing type config entity.
drealty.type.*:
  type: config_entity
  label: 'Listing type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        drealty:
          type: drealty.settings.drealty

# Listing type module settings.
drealty.settings.drealty:
  type: mapping
  label: 'Listing type settings'
  mapping:
    options:
      type: mapping
      label: 'Publishing options'
      mapping:
        status:
          type: boolean
          label: 'Published'
        promote:
          type: boolean
          label: 'Promoted to front page'
        sticky:
          type: boolean
          label: 'Sticky at top of lists'
        revision:
          type: boolean
          label: 'Create new revision'
